config: conf_Conformer/train_asr_transformer.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/asr_train_asr_transformer_raw_bpe_normalize_confnorm_varsFalse
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: 4
dist_rank: 0
local_rank: 0
dist_master_addr: localhost
dist_master_port: 45521
dist_launcher: null
multiprocessing_distributed: true
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 140
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 4
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_tensorboard: true
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 16000000
valid_batch_bins: null
train_shape_file:
- exp/asr_stats_raw/train/speech_shape
- exp/asr_stats_raw/train/text_shape.bpe
valid_shape_file:
- exp/asr_stats_raw/valid/speech_shape
- exp/asr_stats_raw/valid/text_shape.bpe
batch_type: numel
valid_batch_type: null
fold_length:
- 80000
- 150
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - /nlsasfs/home/nltm-pilot/anishb/dump/raw/gramvaani_challenge/dataset100/wav.scp
    - speech
    - sound
-   - /nlsasfs/home/nltm-pilot/anishb/dump/raw/gramvaani_challenge/dataset100/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - /nlsasfs/home/nltm-pilot/anishb/dump/raw/gramvaani_challenge/dataset_dev5h/wav.scp
    - speech
    - sound
-   - /nlsasfs/home/nltm-pilot/anishb/dump/raw/gramvaani_challenge/dataset_dev5h/text
    - text
    - text
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000
token_list:
- <blank>
- <unk>
- ▁के
- ▁है
- ▁की
- र
- ी
- ▁में
- ा
- न
- ल
- ▁को
- े
- ▁ऐसी
- म
- ▁का
- क
- ▁और
- ो
- त
- स
- ों
- ▁हैं
- ि
- ▁कर
- ु
- ह
- द
- ▁अ
- ना
- ने
- ता
- व
- ट
- ू
- प
- ▁भी
- ▁स
- ▁आ
- ज
- य
- ▁हो
- ▁इस
- ▁ने
- वा
- ▁ब
- ▁लिए
- श
- ▁तो
- ्र
- ▁एक
- ▁न
- ▁नहीं
- ं
- ब
- ▁
- ग
- ▁से
- ▁आरोप
- ▁प्र
- री
- ध
- र्
- ▁क
- ित
- ्
- ▁श
- ला
- ▁च
- ▁म
- रा
- ▁ज
- ती
- िक
- ▁प
- ▁द
- ते
- ▁जो
- ▁ही
- च
- ▁पर
- ▁ग
- ाई
- ै
- ▁मई
- ▁वि
- ▁भ
- ▁रहा
- ▁जा
- ▁मैं
- ▁र
- ▁गया
- ▁साथ
- ्य
- ण
- ▁मोबाइल
- ▁रहे
- ▁मिल
- ▁किया
- ंग
- ▁पा
- ▁दो
- ड
- ▁उ
- ▁फ
- ▁हम
- ▁हूँ
- ▁व
- ▁यह
- नी
- ▁तक
- ▁सा
- या
- ▁ह
- ▁त
- ▁रही
- ▁सं
- ▁नि
- ्या
- ली
- मा
- ड़
- ख
- ▁सरकार
- ▁ख
- का
- ▁करने
- ▁या
- ंद
- इ
- ▁मा
- ▁आप
- ाय
- ▁कुमार
- फ
- क्ष
- ▁वाणी
- ▁इ
- त्
- ▁ए
- थ
- ▁जी
- त्र
- ▁आज
- ए
- ▁रा
- ▁धन्यवाद
- कर
- ौ
- ▁बी
- िया
- भ
- ▁था
- ▁नमस्कार
- ▁दे
- ियों
- ▁ये
- ▁ल
- ▁सम
- ▁कुछ
- ▁कम
- स्त
- ▁दिया
- ेश
- ▁ले
- ▁सभी
- ▁ड
- ▁सौ
- ▁अपने
- ▁मु
- ▁लोग
- ष
- ँ
- सा
- ▁छ
- ▁अब
- ▁वा
- ान
- ▁सी
- ▁बात
- ठ
- ें
- ▁बिहार
- ▁जिला
- रे
- ▁ध
- ▁वो
- ▁सु
- ्त
- ▁क्या
- ले
- ्म
- ंड
- गा
- ▁हजार
- ्व
- को
- ▁लग
- ▁बहुत
- के
- ▁कहा
- ॉ
- ओं
- ▁ला
- दा
- ▁खा
- ▁कोई
- ▁हर
- बा
- ▁हुए
- ▁तीन
- ▁कि
- की
- ▁करते
- ▁इन
- ▁लेकिन
- ▁चाहिए
- ▁द्वारा
- ▁हमारे
- ▁कारण
- सी
- ▁बाद
- ▁किसान
- ▁प्रखंड
- ▁लेकर
- ▁भारत
- ▁बा
- पुर
- ▁हा
- ▁बना
- ▁दिन
- ▁खबर
- ▁यहाँ
- ज़
- पा
- मान
- ▁जाता
- ▁होने
- ये
- ▁लोगो
- ीय
- ▁ट
- ▁बे
- ▁योजना
- ▁गयी
- ▁ना
- ▁देश
- ▁तरह
- ल्
- ▁पंचायत
- ▁नाम
- ▁ओ
- ▁घर
- ▁सब
- ▁पी
- ''''
- ति
- ▁दी
- ▁वाले
- टी
- ▁सि
- ▁बता
- से
- ▁बन
- ▁गाँव
- िल
- ▁सुन
- ▁घ
- ्प
- ंत
- ▁करना
- स्ट
- ▁नही
- ▁लगा
- ▁बढ़
- दी
- ▁काम
- ▁हुआ
- ▁पे
- ▁रख
- ▁जाए
- ▁पानी
- ड़ा
- ▁देख
- ▁राज
- ▁इसके
- ▁उस
- हा
- िय
- ▁रो
- ▁होगा
- घ
- ▁किसी
- ▁राज्य
- ▁कई
- रण
- ▁उन
- ▁बि
- ▁रह
- ▁क्षेत्र
- ▁जिस
- ▁गु
- ्स
- िन
- ंक
- जी
- शन
- ेगा
- जा
- ▁कार्य
- ▁पहले
- ▁जन
- ▁हाँ
- ुल
- िंग
- ▁थी
- ▁चल
- ▁मुंगेर
- ▁अभी
- ▁मान
- ▁मे
- ▁होता
- ▁जब
- ष्ट
- ्ता
- वि
- ▁बोल
- ाव
- ▁थे
- ▁समय
- ▁पड़
- ▁मन
- ंस
- ▁मधुबनी
- ▁एस
- कार
- ▁प्रति
- ▁मह
- ▁दु
- भा
- ▁बार
- ई
- ड़ी
- ▁भर
- ▁बच्चों
- ंट
- र्म
- ▁सिंह
- ▁केंद्र
- ▁मि
- ▁गए
- ▁पै
- ंज
- ▁दस
- ▁अगर
- ▁गा
- ▁खेल
- फ़
- टा
- ूर
- र्थ
- वे
- टर
- ▁ता
- ▁साल
- ाया
- ▁अपना
- ▁उप
- ▁विभाग
- ▁पास
- गत
- ▁फिर
- ▁होती
- ▁बच
- ▁शिक्षा
- ्च
- ▁छह
- भाव
- ेंगे
- ▁मो
- ▁रूपए
- e
- ▁स्कूल
- ▁ऐसे
- ओ
- ्ट
- ़
- ▁अपनी
- ▁झारखण्ड
- शा
- ▁हुई
- ▁जानकारी
- ियो
- ▁जाने
- ▁जिले
- ▁वर्ष
- ढ़
- ▁ते
- चा
- ▁बताया
- ▁हज़ार
- ▁आई
- ▁दोस्तों
- ▁रे
- ▁वही
- ोर
- ▁डी
- गी
- ▁परि
- धि
- ▁जाती
- ंच
- ▁राम
- ▁अस
- ▁कु
- न्द
- ▁तथा
- ाने
- ▁रूप
- स्थ
- ▁ज़
- ▁टी
- ▁लो
- ▁अधिक
- ▁अनु
- िट
- ▁लिया
- ऑ
- ▁समाज
- ▁महिला
- ▁पद
- दान
- ▁एवं
- ▁चौ
- ▁रिपोर्ट
- झ
- ▁करे
- ▁शहर
- ▁शिक्षक
- ▁परीक्षा
- ▁कल
- ▁धनबाद
- ▁लोगों
- ▁विकास
- दार
- हार
- ▁सरकारी
- ▁झ
- ▁मेरा
- पन
- ▁हि
- ▁ग्राम
- ▁कार्यक्रम
- ▁परिवार
- ▁व्यवस्था
- ्न
- ▁शुरू
- चार
- ृ
- ▁जनता
- ▁लाख
- ▁छात्र
- िका
- ▁नंबर
- ▁होगी
- ▁बारे
- ▁इससे
- ृत
- वर
- ▁देने
- ▁पि
- ▁ज्यादा
- ▁कह
- िस
- ▁चला
- ▁लाभ
- ▁आपको
- ▁आर
- ▁सकते
- ेगी
- ▁श्रोताओं
- ▁स्
- ▁मंत्री
- ▁समस्या
- म्ब
- ▁बु
- ▁प्रकार
- ▁बंद
- ▁उन्होंने
- ेंट
- ▁गो
- ▁पो
- ▁गरीब
- ▁सकता
- ▁जहाँ
- ▁पांच
- ▁वाली
- ▁नौ
- ▁जैसे
- छ
- ▁जल
- ▁उनके
- ्ह
- ▁चार
- आ
- ▁प्रधान
- ग्र
- ▁बिजली
- ▁जान
- ▁मजदूर
- ▁परेशान
- ▁ग्रामीण
- ▁जगह
- ▁कभी
- षण
- ▁पढ़
- ▁मीडिया
- ▁टीम
- ▁उसके
- धार
- ▁स्व
- द्ध
- ▁सदर
- डी
- ▁आम
- ▁खेत
- ▁एवम
- ▁अच्छा
- ▁मांग
- ▁वे
- खा
- ▁बच्चे
- ▁महा
- ▁पुर
- ▁बदल
- ▁सड़क
- ्ति
- ▁पाँच
- ▁अधिकारी
- ▁मध्य
- ▁जायेगा
- ▁कै
- ▁माध्यम
- ▁कहीं
- ▁जिन
- ▁मुख्या
- ▁तैयार
- ▁तब
- ▁बैंक
- ्ज
- ▁सात
- ▁सके
- ▁ठ
- ▁वहाँ
- ▁उन्हें
- ▁निकाल
- ▁मै
- ▁किए
- ▁सबसे
- ▁आपका
- ▁डॉक्टर
- ▁बैठक
- ▁चाहता
- ▁बीच
- ▁वह
- ▁जल्द
- ▁समाचार
- ▁सुविधा
- ▁दर्ज
- ▁सो
- ▁आधार
- ▁नई
- ▁पहुँच
- ▁जिससे
- ▁प्रदेश
- ▁इसका
- क्क
- ▁कहना
- ▁पु
- ▁तहत
- ▁ऐसा
- ▁बारिश
- ▁काफी
- ▁दिख
- ▁जाते
- ▁आने
- ▁सेवा
- ▁कार्ड
- ▁माँ
- ▁अस्पताल
- ▁आठ
- ▁महिलाओं
- ▁जमुई
- उ
- ▁बड़ी
- ▁जीवन
- ▁जरुर
- ▁सही
- ▁निर्
- ▁देना
- बंध
- िये
- ढ
- ▁जारी
- ▁सुबह
- ▁इतन
- ▁अन्य
- ज्ञ
- ▁उठा
- ▁स्वा
- ▁जमा
- ▁रोक
- ▁हमें
- ्वा
- ▁गई
- ▁'
- ▁निर्माण
- ▁पता
- ▁अठारह
- ▁आगे
- ▁बोकारो
- ▁नए
- ▁आपके
- ▁ली
- ▁खास
- ▁बजे
- ▁अधिकार
- ▁जाएगी
- ▁बनाने
- ▁क्यूँकी
- ▁आये
- ▁दीदी
- ▁रेलवे
- ▁आदाब
- ▁उसे
- ▁अध्यक्ष
- ▁इसमें
- ▁खुश
- िए
- ▁M
- ▁देखा
- ▁भारतीय
- ▁ताकि
- ▁पिछले
- i
- ▁बाल
- ियाँ
- ▁दिनों
- ▁होते
- t
- ▁देवी
- ▁आदि
- p
- ▁दवा
- ▁पुलिस
- n
- m
- l
- ▁स्थिति
- ▁बढ़ा
- '#'
- c
- o
- ▁वेतन
- पूर्ण
- ▁समझ
- ▁दबा
- ▁करके
- ▁पहल
- ▁नगर
- ▁सकती
- ▁विश्व
- ▁ग्र
- ▁करोड़
- ▁पत्र
- ▁तू
- ▁स्थान
- ▁स्तर
- ▁इसलिए
- ▁देते
- ▁तीस
- ▁दौरान
- ▁दूर
- ▁श्री
- ▁लड़क
- ▁तुम
- ▁फसल
- ▁बारह
- ▁उनकी
- ▁अभियान
- ▁करेंगे
- ▁मुझे
- ▁जिसमे
- ▁पदाधिकारी
- ▁संख्या
- ▁पूरा
- क्स
- ▁जाएगा
- ▁ट्र
- ▁जाँच
- ▁सुरक्षा
- ▁अनुसार
- न्द्र
- ▁पूरी
- ▁लगभग
- ▁पचास
- ▁कैसे
- ▁व्यक्ति
- ▁शौचालय
- ▁स्वच्छ
- स्क
- ▁सुना
- ▁ट्रेन
- ▁गिर
- ▁श्रोताओ
- ▁रहने
- ▁मेरे
- ▁भाग
- ▁पूर्व
- ▁नियम
- ▁दिवस
- ▁उपलब्ध
- ▁सुर्खिया
- ▁पटना
- ▁विद्यालय
- ▁स्वास्थ्य
- ▁अच्छी
- ▁जिसके
- ▁आवाज़
- ▁पैसा
- युक्त
- ▁जुड़
- ▁सोच
- ▁मलेरिया
- एँ
- ▁निर्देश
- ▁हमारी
- ▁लिख
- ▁विद्द्यालय
- ▁तरफ
- ▁सर्व
- ▁मोबाइलवाणी
- ▁दिल
- ▁दोनो
- ▁चुनाव
- ▁ढ
- ▁पूजा
- ▁बच्चा
- ▁बैठ
- ▁शराब
- ▁काफ़ी
- ▁मौसम
- ▁उनका
- ▁दिए
- ▁आयोजन
- ▁सितम्बर
- ▁A
- ▁सदस्य
- ▁शिव
- ः
- ▁परन्तु
- ▁सोलह
- ▁बड़े
- ▁किलो
- ▁महीने
- ▁नम्बर
- ▁विषय
- ▁साफ़
- ▁स्वस्थ
- ेक्ट
- ▁युवा
- ▁शामिल
- ▁हमारा
- ▁समिति
- ▁आवास
- ▁बाजार
- ▁दुसरे
- ▁क्यूँ
- ▁उसका
- ▁मंडल
- ▁न्यू
- ▁पेंशन
- ▁प्ल
- ▁विचार
- ▁अगस्त
- ▁श्रोता
- ▁पंद्रह
- ▁महतो
- ▁कानून
- ▁अलग
- ▁अभि
- ▁घटना
- ▁कार्यालय
- ▁करीब
- ▁मैच
- ▁संस्था
- ▁स्थित
- ▁भेज
- ▁मरीज
- ▁प्राप्त
- ▁सिकंदरा
- ▁वगैरह
- ▁सफाई
- ▁बेहतर
- ▁सिर्फ
- ▁होंगे
- ▁मच्छर
- ▁आवेदन
- ▁ध्यान
- ▁कोर्ट
- ▁दुकान
- ▁उन्नीस
- ▁प्रशासन
- ▁मोबइलवाणी
- ऊ
- ▁कर्मियों
- ▁लागू
- ▁ग्यारह
- ▁दिल्ली
- ▁प्रतिशत
- ▁उपयोग
- ▁अंतर्गत
- ▁जिंदगी
- ▁कर्मचारी
- ▁योग
- ▁स्टेशन
- ▁मोदी
- A
- ▁जागरूक
- ▁बाहर
- ▁मौके
- ▁मामले
- ▁उसमे
- ▁जबकि
- ▁खिलाफ
- ▁कॉलेज
- ▁सूचना
- ▁आवश्यक
- ▁सामना
- ▁कृषि
- ▁इंग्लैंड
- ▁सहित
- ▁चर्चा
- ▁सामने
- ▁विशेष
- ▁वजह
- ▁प्रखण्ड
- ▁चौबीस
- ▁दीपक
- ▁वार्ड
- ▁अवसर
- ▁इलाज
- ▁ज़रूर
- ▁वैसे
- ▁पांडे
- ▁सफल
- ▁चाहे
- ▁शिकायत
- ▁लगातार
- ▁दूसरी
- ▁पेट्रोल
- ▁ठीक
- ▁टेस्ट
- ▁मधु
- ▁ऊपर
- ▁सम्बंधित
- ▁उपस्थित
- ▁इलाक
- ▁खुद
- ▁खर्च
- ▁जीविका
- ▁घंटे
- ▁वर्ग
- ▁चीज
- ▁सचिव
- ▁यदि
- ▁सम्बन्ध
- ▁यु
- ▁प्रदर्शन
- ▁मौजूद
- ▁मुखिया
- ▁प्रसाशन
- ण्ड
- ▁वितरण
- ▁बोर्ड
- ▁मतलब
- ▁कौन
- ▁डीजल
- ▁जायेंगे
- ▁कर्मचारियों
- ▁मुख्यमंत्री
- ▁खराब
- ▁इंडिया
- ▁चौदह
- ▁गर्मी
- ▁मुक्त
- ▁भूमि
- ▁भविष्य
- ▁पुरुष
- ▁सोमवार
- ▁उम्र
- ▁रुप
- अ
- ▁डेल्ही
- ▁दिलीप
- ▁खरीद
- ▁अक्टूबर
- ▁फीसदी
- ▁चाहते
- ▁पन्द्रह
- ▁वृद्ध
- ▁प्रयास
- ▁अच्छे
- ▁आखिर
- ▁सत्रह
- ▁खुटौना
- ▁पूछ
- ▁रोजगार
- हत्तर
- ▁संतोष
- ▁प्राथमिक
- ▁नज़र
- ▁धीरे
- ▁खजौली
- ▁प्रतिक्रिया
- ▁रविवार
- ▁रांची
- ▁चुकी
- ▁प्रसाद
- ▁आयोजित
- ▁भोजन
- ▁न्याय
- ▁शांति
- ▁बुधवार
- ▁तेरह
- ▁राशि
- ▁आवाज
- ▁आयोग
- ▁भुगतान
- ▁जुलाई
- ▁मंदिर
- ▁ख़बरों
- ▁बावजूद
- ▁पौध
- N
- ▁छोड़
- ▁अपराध
- ▁दोपहर
- ▁आदमी
- ▁मुताबिक
- ▁चूका
- ▁खिला
- ▁गाँधी
- ','
- '['
- ']'
- ऐ
- औ
- I
- R
- E
- L
- O
- H
- ऋ
- K
- T
- U
- D
- '-'
- Y
- S
- J
- ञ
- B
- M
- W
- a
- G
- P
- C
- k
- V
- .
- b
- ':'
- ॅ
- F
- h
- ।
- ऍ
- s
- ङ
- X
- y
- \
- ऱ
- d
- Z
- r
- <sos/eos>
init: xavier_uniform
input_size: null
ctc_conf:
    dropout_rate: 0.0
    ctc_type: builtin
    reduce: true
    ignore_nan_grad: true
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
use_preprocessor: true
token_type: bpe
bpemodel: data/token_list/bpe_unigram1000/bpe.model
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
frontend: default
frontend_conf:
    fs: 16k
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
normalize: global_mvn
normalize_conf:
    stats_file: exp/asr_stats_raw/train/feats_stats.npz
    norm_vars: false
preencoder: null
preencoder_conf: {}
encoder: transformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
postencoder: null
postencoder_conf: {}
decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
required:
- output_dir
- token_list
version: 0.10.3a2
distributed: true
